name: Check Commit Message Format

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check commit message format
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run JavaScript action
        uses: actions/github-script@v4
        with:
          script: |
            const { execSync } = require('child_process');

            try {
              const commitMessage = execSync('git log --format=%B -n 1 HEAD').toString().trim();
              console.log(`Commit message: ${commitMessage}`);

              const commitFormat = '#Esto es un ejemplo';
              const normalizedCommitMessage = commitMessage
                .normalize('NFD')
                .replace(/[\u0300-\u036f]/g, '')
                .toLowerCase();
              const normalizedCommitFormat = commitFormat
                .normalize('NFD')
                .replace(/[\u0300-\u036f]/g, '')
                .toLowerCase();

              console.log(normalizedCommitMessage);
              console.log(normalizedCommitFormat);

              if (!normalizedCommitMessage.match(normalizedCommitFormat)) {
                console.error('error: invalid commit message format');
                process.exit(1);
              }
            } catch (error) {
              console.error(`Error executing script: ${error.message}`);
              process.exit(1);
            }
